CREATE TABLE users (
  user_id bigint NOT NULL DEFAULT nextval('users_user_id_seq'::regclass),
  name character varying NOT NULL,
  email character varying NOT NULL UNIQUE,
  phone character varying,
  profile_pic character varying,
  address character varying,
  pan_number character varying,
  aadhaar_number character varying,
  is_verified boolean DEFAULT false,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  username character varying,
  id_proof character varying,
  supabase_id uuid UNIQUE,
  status character varying NOT NULL DEFAULT 'ACTIVE'::character varying,
  verified boolean NOT NULL DEFAULT false,
  avatar character varying,
  subscribed boolean NOT NULL DEFAULT false,
  CONSTRAINT users_pkey PRIMARY KEY (user_id)
);