CREATE TABLE listings (
  product_id bigint NOT NULL DEFAULT nextval('listings_product_id_seq'::regclass),
  owner_id bigint,
  serial_or_imei character varying UNIQUE,
  brand character varying,
  model character varying,
  purchase_price numeric,
  daily_rate numeric NOT NULL,
  security_deposit numeric NOT NULL,
  health_score integer CHECK (health_score >= 1 AND health_score <= 100),
  location character varying,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  days integer,
  description character varying,
  product_name character varying,
  category character varying,
  productspec jsonb,
  available_from date,
  available_to date,
  maximum_rental_days integer,
  minimum_rental_days integer,
  purchase_year integer,
  is_available boolean NOT NULL DEFAULT true,
  approval_status character varying NOT NULL DEFAULT 'PENDING'::character varying,
  CONSTRAINT listings_pkey PRIMARY KEY (product_id),
  CONSTRAINT listings_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.users(user_id)
);