spring.application.name=Orrabackend
spring.config.import=optional:file:.env[.properties]
# ── Datasource ───────────────────────────────────────────────
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0

spring.datasource.username=postgres.jnizlhfupndwxuujpgku
spring.datasource.password=Scram@3779Ameo

spring.datasource.driver-class-name=org.postgresql.Driver

# ── SSL Fix ──────────────────────────────────────────────────
spring.datasource.hikari.data-source-properties.sslmode=require
spring.datasource.hikari.data-source-properties.prepareThreshold=0
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5

# ── JPA ──────────────────────────────────────────────────────
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# ── RabbitMQ ─────────────────────────────────────────────────
#spring.rabbitmq.host=localhost
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=guest
#spring.rabbitmq.password=guest
spring.rabbitmq.host=warthog.lmq.cloudamqp.com
spring.rabbitmq.port=5671
spring.rabbitmq.username=sxfntcvu
spring.rabbitmq.password=XjL2Ml_4xeQBqOb2oLznRJ5Gvw19JIst
spring.rabbitmq.virtual-host=sxfntcvu
spring.rabbitmq.ssl.enabled=true

app.rabbitmq.exchange=payment.exchange
app.rabbitmq.payment-success-queue=payment.success.queue
app.rabbitmq.booking-confirmed-queue=booking.confirmed.queue
app.rabbitmq.payment-success-routing-key=payment.success
app.rabbitmq.booking-confirmed-routing-key=booking.confirmed

#spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
#spring.datasource.username=postgres.jnizlhfupndwxuujpgku
#spring.datasource.password=Scram@3779Ameo
#spring.datasource.driver-class-name=org.postgresql.Driver
#
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
server.port=8081
#logging.level.org.springframework.security=DEBUG

spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=omkathar0@gmail.com
spring.mail.password=ywrs iuvy jiwo ajfy

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

supabase.url=${SUPABASE_URL}
supabase.secret=${SUPABASE_SECRET}
supabase.bucket=${SUPABASE_BUCKET}

#spring.main.lazy-initialization=true
spring.jpa.properties.hibernate.transaction.jta.platform=disabled

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB
server.tomcat.max-http-form-post-size=25MB
server.tomcat.max-swallow-size=25MB
# For JSON body specifically:
spring.codec.max-in-memory-size=25MB
server.tomcat.connection-timeout=60000